spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null  # 返回给前端的值为null时不返回
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/

server:
  servlet:
    context-path: /sell
  port: 8081

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.ws.LoggerTest: debug
